Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	make_mosaic
	1
Select jobs to execute...

[Fri Jun 11 13:21:28 2021]
rule make_mosaic:
    input: config/Field_240_m20.yaml
    output: results/Panstarrs_Mosiac_240_m20.fits
    jobid: 0

[Fri Jun 11 13:21:28 2021]
Error in rule make_mosaic:
    jobid: 0
    output: results/Panstarrs_Mosiac_240_m20.fits

RuleException:
CalledProcessError in line 7 of /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile:
Command 'set -euo pipefail;  /opt/anaconda3/envs/snakemake/bin/python3.9 /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/scripts/tmpgglzxrml.make_mosaic.py' returned non-zero exit status 1.
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
  File "/Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile", line 7, in __rule_make_mosaic
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 574, in _callback
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in cached_or_run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2390, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/log/2021-06-11T132126.894407.snakemake.log
