Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	make_mosaic
	1	run_profound_on_mosaic
	2
Select jobs to execute...

[Fri Jun 11 14:25:08 2021]
rule make_mosaic:
    input: config/Field_240_m20.yaml
    output: results/Mosaics/Panstarrs_Mosiac_240_m20.fits
    jobid: 3

[Fri Jun 11 14:31:29 2021]
Finished job 3.
1 of 2 steps (50%) done
Select jobs to execute...

[Fri Jun 11 14:31:29 2021]
rule run_profound_on_mosaic:
    input: config/Field_240_m20.yaml, results/Mosaics/Panstarrs_Mosiac_240_m20.fits
    output: results/SkyMasks/Mosaic/segmap_StarField_240_-22.fits, results/ProfoundCatalogues/profound_catalogue_240_-22.csv
    jobid: 2

Terminating processes on user request, this might take some time.
[Fri Jun 11 14:34:37 2021]
Error in rule run_profound_on_mosaic:
    jobid: 2
    output: results/SkyMasks/Mosaic/segmap_StarField_240_-22.fits, results/ProfoundCatalogues/profound_catalogue_240_-22.csv

RuleException:
CalledProcessError in line 30 of /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile:
Command 'set -euo pipefail;  /opt/anaconda3/envs/snakemake/bin/python3.9 /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/scripts/tmpl3uqprb5.make_mosaic.py' died with <Signals.SIGINT: 2>.
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
  File "/Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile", line 30, in __rule_run_profound_on_mosaic
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 574, in _callback
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in cached_or_run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2390, in run_wrapper
Complete log: /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/log/2021-06-11T142507.694469.snakemake.log
